x = int(1.2)
y = int(1)
z = int("3")
print(x,y,z)
print(type(x),type(y),type(z))
a = float(10)
b = float("10.0")
e = float("10")
c = float(10.0)
print(a,b,c,e)
f = str(1)
g = str("10.0")
h = str(10.0)
print(f,g,h)
print(type(f),type(g),type(h))